<?php
namespace ScratchByPHP\Studio;
use ScratchByPHP\Session; use ScratchByPHP\Cache\CacheInterface; use ScratchByPHP\Config; use ScratchByPHP\Http\HttpClient; use ScratchByPHP\Exceptions\ApiException;
final class Studio {
    public function __construct(private string $id,private ?Session $session=null,private ?HttpClient $client=null,private ?CacheInterface $cache=null,private ?Config $config=null){}
    private function http():HttpClient{return $this->client??$this->session?->http()??new HttpClient(['Accept'=>'application/json'],null,$this->config);} private function rs():Session{if(!$this->session)throw new \LogicException('Authenticated Session gerekir.');return $this->session;}
    private function ok($r,string $a):array{if($r->status<200||$r->status>=300)throw new ApiException($a.' başarısız. HTTP '.$r->status.': '.$r->body);return $r->json()?:['success'=>true,'status'=>$r->status];}
    public function get():array{$key='studio:'.$this->id;if($this->cache&&$this->cache->has($key))return $this->cache->get($key);$d=$this->http()->get('https://api.scratch.mit.edu/studios/'.rawurlencode($this->id))->json();$this->cache?->set($key,$d,(int)($this->config?->get('cache_ttl_studio',$this->config?->get('cache_ttl',60)??60)??60));return $d;} public function refresh():array{$this->cache?->delete('studio:'.$this->id);return $this->get();} public function id():string{return $this->id;} public function title():?string{return $this->get()['title']??null;}
    public function projects(int $l=20,int $o=0):array{return $this->http()->get('https://api.scratch.mit.edu/studios/'.$this->id.'/projects?limit='.$l.'&offset='.$o)->json();}
    public function allProjects(int $pageSize=40,int $maxProjects=2000):array{$pageSize=max(1,min(40,$pageSize));$maxProjects=max(1,$maxProjects);$all=[];$offset=0;while(count($all)<$maxProjects){$take=min($pageSize,$maxProjects-count($all));$rows=$this->projects($take,$offset);if(!$rows)break;foreach($rows as $row){if(!is_array($row)||!isset($row['id']))continue;$all[(string)$row['id']]=$row;} $count=count($rows);$offset+=$count;if($count<$take)break;}return array_values($all);}
    public function curators(int $l=20,int $o=0):array{return $this->http()->get('https://api.scratch.mit.edu/studios/'.$this->id.'/curators?limit='.$l.'&offset='.$o)->json();} public function managers(int $l=20,int $o=0):array{return $this->http()->get('https://api.scratch.mit.edu/studios/'.$this->id.'/managers?limit='.$l.'&offset='.$o)->json();}
    public function comments(int $l=20,int $o=0):array{return $this->http()->get('https://api.scratch.mit.edu/studios/'.$this->id.'/comments?limit='.$l.'&offset='.$o)->json();} public function commentReplies(int|string $id,int $l=20,int $o=0):array{return $this->http()->get('https://api.scratch.mit.edu/studios/'.$this->id.'/comments/'.$id.'/replies?limit='.$l.'&offset='.$o)->json();}
    public function addProject(int|string $p):array{$this->rs();return $this->ok($this->http()->post('https://api.scratch.mit.edu/studios/'.$this->id.'/project/'.$p),'Proje ekleme');} public function removeProject(int|string $p):array{$this->rs();return $this->ok($this->http()->delete('https://api.scratch.mit.edu/studios/'.$this->id.'/project/'.$p),'Proje çıkarma');}
    public function acceptInvite():array{$s=$this->rs();return $this->ok($this->http()->put('https://scratch.mit.edu/site-api/users/curators-in/'.$this->id.'/add/?usernames='.rawurlencode((string)$s->username())),'Studio davet kabul');}
    public function yourRole():array{$s=$this->rs();return $this->http()->get('https://api.scratch.mit.edu/studios/'.$this->id.'/users/'.rawurlencode((string)$s->username()))->json();}
    public function inviteCurator(string $u):array{$this->rs();return $this->ok($this->http()->put('https://scratch.mit.edu/site-api/users/curators-in/'.$this->id.'/invite_curator/?usernames='.rawurlencode($u)),'Curator davet');} public function promoteCurator(string $u):array{$this->rs();return $this->ok($this->http()->put('https://scratch.mit.edu/site-api/users/curators-in/'.$this->id.'/promote/?usernames='.rawurlencode($u)),'Curator promote');} public function removeCurator(string $u):array{$this->rs();return $this->ok($this->http()->put('https://scratch.mit.edu/site-api/users/curators-in/'.$this->id.'/remove/?usernames='.rawurlencode($u)),'Curator çıkar');} public function leave():array{return $this->removeCurator((string)$this->rs()->username());}
    public function transferOwnership(string $u,string $password):array{$this->rs();return $this->ok($this->http()->put('https://api.scratch.mit.edu/studios/'.$this->id.'/transfer/'.rawurlencode($u),['password'=>$password]),'Ownership transfer');}
    public function follow():array{$s=$this->rs();return $this->ok($this->http()->put('https://scratch.mit.edu/site-api/users/bookmarkers/'.$this->id.'/add/?usernames='.rawurlencode((string)$s->username())),'Studio follow');} public function unfollow():array{$s=$this->rs();return $this->ok($this->http()->put('https://scratch.mit.edu/site-api/users/bookmarkers/'.$this->id.'/remove/?usernames='.rawurlencode((string)$s->username())),'Studio unfollow');}
    public function setFields(array $f):array{$this->rs();return $this->ok($this->http()->put('https://scratch.mit.edu/site-api/galleries/all/'.$this->id.'/',$f),'Studio alan güncelleme');} public function setTitle(string $t):array{return $this->setFields(['title'=>$t]);} public function setDescription(string $d):array{return $this->setFields(['description'=>$d."\n"]);} public function openProjects():array{$this->rs();return $this->ok($this->http()->put('https://scratch.mit.edu/site-api/galleries/'.$this->id.'/mark/open/'),'Projeleri aç');} public function closeProjects():array{$this->rs();return $this->ok($this->http()->put('https://scratch.mit.edu/site-api/galleries/'.$this->id.'/mark/closed/'),'Projeleri kapat');}
    public function setThumbnail(string $path):array{$this->rs();if(!is_file($path))throw new \InvalidArgumentException('Görsel bulunamadı.');return $this->ok($this->http()->multipart('POST','https://scratch.mit.edu/site-api/galleries/all/'.$this->id.'/', ['file'=>new \CURLFile($path)]),'Studio thumbnail');}
    public function postComment(string $c,int|string|null $p=null,int|string|null $ce=null):array{$this->rs();$d=['commentee_id'=>$ce??'','content'=>trim($c),'parent_id'=>$p??''];if($d['content']==='')throw new \InvalidArgumentException('Yorum boş.');return $this->ok($this->http()->post('https://api.scratch.mit.edu/proxy/comments/studio/'.$this->id.'/',$d,['Content-Type'=>'application/json']),'Studio yorum');} public function replyComment(string $c,int|string $p,int|string|null $ce=null):array{return $this->postComment($c,$p,$ce);} public function deleteComment(int|string $id):array{$this->rs();return $this->ok($this->http()->delete('https://api.scratch.mit.edu/proxy/comments/studio/'.$this->id.'/comment/'.$id.'/'),'Studio yorum sil');} public function reportComment(int|string $id):array{$this->rs();return $this->ok($this->http()->delete('https://api.scratch.mit.edu/proxy/comments/studio/'.$this->id.'/comment/'.$id.'/report'),'Studio yorum report');}

    public function toArray(): array { return $this->get(); }
    public function toJson(int $flags=JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES): string { return (string)json_encode($this->get(),$flags); }
    public function infoDto(): \ScratchByPHP\DTO\StudioInfo { return \ScratchByPHP\DTO\StudioInfo::fromArray($this->get()); }
    public function projectsPaginator(): \ScratchByPHP\Pagination\Paginator { return new \ScratchByPHP\Pagination\Paginator(fn($l,$o)=>$this->projects($l,$o),fn($r)=>new \ScratchByPHP\Project\Project((string)($r['id']??''),$this->session,$this->client,$this->cache,$this->config)); }
    public function curatorsCollection(int $limit=20,int $offset=0): \ScratchByPHP\Collections\Collection { return new \ScratchByPHP\Collections\Collection(array_map(fn($r)=>new \ScratchByPHP\User\User((string)($r['username']??''),$this->session,$this->client,$this->cache,$this->config),$this->curators($limit,$offset))); }
    public function commentsCollection(int $limit=20,int $offset=0): \ScratchByPHP\Collections\Collection { return new \ScratchByPHP\Collections\Collection(array_map(fn($r)=>\ScratchByPHP\Comment\Comment::fromArray($r,$this->session,'studio',$this->id),$this->comments($limit,$offset))); }

}
