<?php
require dirname(__DIR__).'/autoload.php';
use ScratchByPHP\Scratch;use ScratchByPHP\Collections\Collection;use ScratchByPHP\Pagination\Paginator;use ScratchByPHP\Cache\MemoryCache;use ScratchByPHP\DTO\ProjectStats;use ScratchByPHP\Comment\Comment;use ScratchByPHP\Analysis\ProjectAnalyzer;use ScratchByPHP\Analysis\ProjectDiff;use ScratchByPHP\Support\RateLimiter;use ScratchByPHP\Debug\DebugCollector;
$tests=[];$t=function(string $name,callable $fn)use(&$tests){try{$v=$fn();$tests[$name]=['ok'=>(bool)$v];}catch(Throwable $e){$tests[$name]=['ok'=>false,'error'=>$e->getMessage()];}};
$t('01 config/version',fn()=>Scratch::version()==='0.8.5' && (new Scratch(['timeout'=>9]))->config()->get('timeout')===9);
$t('02 pagination',function(){ $p=new Paginator(fn($l,$o)=>array_slice(range(1,7),$o,$l)); return $p->limit(3)->page(2)->get()->all()===[4,5,6];});
$t('03 models/collections',fn()=>class_exists(Collection::class)&&method_exists(ScratchByPHP\User\User::class,'projectsCollection'));
$t('04 comment model',fn()=>Comment::fromArray(['id'=>1,'content'=>'x'])->content()==='x');
$t('05 collection',fn()=>(new Collection([1,2,3,4]))->filter(fn($x)=>$x%2===0)->map(fn($x)=>$x*10)->all()===[20,40]);
$t('06 cache',function(){ $c=new MemoryCache();$c->set('x',7);return $c->has('x')&&$c->get('x')===7;});
$t('07 rate limiter',fn()=>method_exists(RateLimiter::class,'maxRequests')&&RateLimiter::retryAfter(['retry-after'=>['2']])===2);
$t('08 batch',fn()=>method_exists(ScratchByPHP\Batch\BatchBuilder::class,'project'));
$t('09 parallel',fn()=>method_exists(ScratchByPHP\Batch\ParallelClient::class,'run'));
$t('10 cloud manager',fn()=>method_exists(ScratchByPHP\Cloud\CloudConnection::class,'setMany')&&method_exists(ScratchByPHP\Cloud\CloudConnection::class,'variables'));
$t('11 cloud history',fn()=>method_exists(ScratchByPHP\Cloud\CloudConnection::class,'history'));
$t('12 cloud database 2',fn()=>method_exists(ScratchByPHP\Cloud\CloudDatabase::class,'increment')&&method_exists(ScratchByPHP\Cloud\CloudDatabase::class,'clear'));
$t('13 cloud requests 2',fn()=>method_exists(ScratchByPHP\Cloud\CloudRequests::class,'route')&&method_exists(ScratchByPHP\Cloud\CloudRequests::class,'middleware'));
$t('14 watcher',fn()=>class_exists(ScratchByPHP\Watch\Watcher::class));
$t('15 analyzer 2',function(){ $a=ProjectAnalyzer::fromJson(['targets'=>[]]);return method_exists($a,'warnings')&&method_exists($a,'complexityScore');});
$t('16 project diff',fn()=>(new ProjectDiff(['targets'=>[]],['targets'=>[]]))->toArray()['added_sprites']===[]);
$t('17 sb3 tools',fn()=>class_exists(ScratchByPHP\Sb3\Sb3Archive::class)&&method_exists(ScratchByPHP\Project\Project::class,'downloadSb3'));
$t('18 dto',fn()=>(new ProjectStats(1,2,3,4))->views===1);
$t('19 ide/phpdoc surface',fn()=>method_exists(ScratchByPHP\Http\Response::class,'statusCode')&&method_exists(ScratchByPHP\Project\Project::class,'toArray'));
$t('20 phpstan',fn()=>is_file(dirname(__DIR__).'/phpstan.neon'));
$t('21 phpunit',fn()=>is_file(dirname(__DIR__).'/phpunit.xml'));
$t('22 fake',fn()=>Scratch::fake()->fakeProject(1,['title'=>'x'])->project(1)->title()==='x');
$t('23 psr bridges',fn()=>class_exists(ScratchByPHP\Interop\Psr3LoggerAdapter::class)&&class_exists(ScratchByPHP\Cache\Psr16CacheAdapter::class)&&class_exists(ScratchByPHP\Interop\Psr18HttpClientAdapter::class));
$t('24 laravel bridge',fn()=>is_file(dirname(__DIR__).'/integrations/laravel/composer.json'));
$t('26 cli',fn()=>is_file(dirname(__DIR__).'/bin/scratchbyphp'));
$t('27 doctor',fn()=>array_key_exists('php_ok',(new Scratch())->healthCheck(false)));
$t('28 debug',function(){ $d=new DebugCollector();$d->enable();$d->record('x',['token'=>'secret']);return $d->events()[0]['data']['token']==='[REDACTED]';});
$t('29 api checker',fn()=>str_contains((string)file_get_contents(dirname(__DIR__).'/src/Cli/Application.php'),'check-api'));
$t('30 api docs generator',fn()=>is_file(dirname(__DIR__).'/tools/generate-api.php'));
$ok=count(array_filter($tests,fn($x)=>$x['ok']))===count($tests);echo json_encode(['ok'=>$ok,'passed'=>count(array_filter($tests,fn($x)=>$x['ok'])),'total'=>count($tests),'tests'=>$tests],JSON_PRETTY_PRINT|JSON_UNESCAPED_UNICODE)."\n";exit($ok?0:1);
