<?php
namespace ScratchByPHP\Cli;
use ScratchByPHP\Scratch;use ScratchByPHP\Sb3\Sb3Validator;
final class Application
{
 public function run(array $argv):int{$cmd=$argv[1]??'help';$json=in_array('--json',$argv,true);$s=new Scratch();try{return match($cmd){'version'=>$this->emit(['version'=>Scratch::VERSION],$json),'doctor'=>$this->doctor($s,$json),'project'=>$this->project($s,$argv[2]??'104',$json),'user'=>$this->user($s,$argv[2]??'griffpatch',$json),'studio'=>$this->studio($s,$argv[2]??'33703618',$json),'analyze'=>$this->analyze($s,$argv[2]??'104',$json),'check-api'=>$this->checkApi($s,$json),'sb3:validate'=>$this->validate($argv[2]??'', $json),'metrics'=>$this->emit($s->metrics()->summary(),$json),'help'=>$this->help(),default=>$this->fail('Bilinmeyen komut: '.$cmd)};}catch(\Throwable $e){fwrite(STDERR,"ERROR: {$e->getMessage()}\n");return 1;}}
 private function emit(array $d,bool $json):int{if($json)echo json_encode($d,JSON_PRETTY_PRINT|JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES)."\n";else foreach($d as $k=>$v)echo str_pad((string)$k,22).': '.(is_scalar($v)?(is_bool($v)?($v?'OK':'FAIL'):$v):json_encode($v,JSON_UNESCAPED_UNICODE))."\n";return 0;} private function fail(string $s):int{fwrite(STDERR,$s."\n");return 1;}
 private function help():int{echo "ScratchByPHP CLI v0.8.5\n  version [--json]\n  doctor [--json]\n  project <id> [--json]\n  user <username> [--json]\n  studio <id> [--json]\n  analyze <id> [--json]\n  check-api [--json]\n  sb3:validate <file.sb3> [--json]\n  metrics [--json]\n";return 0;}
 private function doctor(Scratch $s,bool $j):int{$h=$s->healthCheck(true);$this->emit($h,$j);return !empty($h['ok'])?0:1;} private function project(Scratch $s,string $id,bool $j):int{$p=$s->project($id);return $this->emit(['id'=>$id,'title'=>$p->title(),'author'=>$p->author(),'views'=>$p->views(),'loves'=>$p->loves(),'favorites'=>$p->favorites()],$j);} private function user(Scratch $s,string $u,bool $j):int{return $this->emit($s->user($u)->get(),$j);} private function studio(Scratch $s,string $id,bool $j):int{return $this->emit($s->studio($id)->get(),$j);} private function analyze(Scratch $s,string $id,bool $j):int{return $this->emit($s->project($id)->analyze()->summary()+['warnings'=>$s->project($id)->analyze()->warnings()],$j);} private function checkApi(Scratch $s,bool $j):int{$r=$s->parallel(['project'=>['url'=>'https://api.scratch.mit.edu/projects/104'],'user'=>['url'=>'https://api.scratch.mit.edu/users/griffpatch'],'news'=>['url'=>'https://api.scratch.mit.edu/news?limit=1']],15,3,1);$this->emit($r,$j);return count(array_filter($r,fn($x)=>empty($x['ok'])))===0?0:1;} private function validate(string $f,bool $j):int{if($f==='')return $this->fail('SB3 yolu gerekli.');$r=(new Sb3Validator())->validate($f);$this->emit($r,$j);return $r['ok']?0:1;}
}
