<?php
namespace ScratchByPHP\Watch;
use ScratchByPHP\Project\Project;
use ScratchByPHP\Scratch;
final class ProjectWatch
{
    private array $handlers=[]; private ?array $last=null; private ?string $stateFile=null; private float $jitter=0.0; private float $backoff=1.5; private EventQueue $queue;
    public function __construct(private Scratch $scratch,private string $id,private float $interval=15.0){$this->queue=new EventQueue();}
    public function onView(callable $c):self{$this->handlers['views'][]=$c;return $this;} public function onLove(callable $c):self{$this->handlers['loves'][]=$c;return $this;} public function onFavorite(callable $c):self{$this->handlers['favorites'][]=$c;return $this;} public function onRemix(callable $c):self{$this->handlers['remixes'][]=$c;return $this;} public function onComment(callable $c):self{$this->handlers['comments'][]=$c;return $this;} public function onShare(callable $c):self{$this->handlers['shared'][]=$c;return $this;} public function onChange(callable $c):self{$this->handlers['*'][]=$c;return $this;}
    public function persistTo(string $file):self{$this->stateFile=$file;if(is_file($file)){$d=json_decode((string)file_get_contents($file),true);if(is_array($d))$this->last=$d;}return $this;}
    public function jitter(float $fraction=0.15):self{$this->jitter=max(0,min(.75,$fraction));return $this;} public function backoff(float $factor=1.5):self{$this->backoff=max(1.0,$factor);return $this;} public function queue():EventQueue{return $this->queue;}
    public function snapshot():array{$p=$this->scratch->project($this->id);$d=$p->refresh();$latest=null;try{$c=$p->comments(1,0);if(isset($c[0])&&is_array($c[0]))$latest=$c[0];}catch(\Throwable){}return ['views'=>(int)($d['stats']['views']??0),'loves'=>(int)($d['stats']['loves']??0),'favorites'=>(int)($d['stats']['favorites']??0),'remixes'=>(int)($d['stats']['remixes']??0),'shared'=>(bool)($d['is_published']??$d['public']??false),'latest_comment_id'=>isset($latest['id'])?(string)$latest['id']:null,'latest_comment'=>$latest,'fetched_at'=>gmdate('c')];}
    public function baseline():array{$this->last=$this->snapshot();$this->save();return $this->last;} public function lastState():?array{return $this->last;}
    public static function diffStates(array $old,array $new):array{$changes=[];foreach(['views','loves','favorites','remixes'] as $f){$a=(int)($old[$f]??0);$b=(int)($new[$f]??0);if($a!==$b)$changes[$f]=[$a,$b];}$a=(bool)($old['shared']??false);$b=(bool)($new['shared']??false);if($a!==$b)$changes['shared']=[$a,$b];$a=$old['latest_comment_id']??null;$b=$new['latest_comment_id']??null;if($a!==$b&&$b!==null)$changes['comments']=[$a,$b];return $changes;}
    public function tick():array{$p=$this->scratch->project($this->id);$now=$this->snapshot();if($this->last===null){$this->last=$now;$this->save();return [];} $changes=self::diffStates($this->last,$now);foreach($changes as $field=>[$old,$new]){$event=['project_id'=>$this->id,'field'=>$field,'before'=>$old,'after'=>$new,'detected_at'=>gmdate('c')];if($field==='comments')$event['comment']=$now['latest_comment']??null;$this->queue->push($event);if($field==='comments'){foreach($this->handlers['comments']??[] as $cb)$cb($now['latest_comment']??null,$old,$p);}else{foreach($this->handlers[$field]??[] as $cb)$cb($new,$old,$p);}foreach($this->handlers['*']??[] as $cb)$cb($field,$new,$old,$p);} $this->last=$now;$this->save();return $changes;}
    public function run(?int $cycles=null):void{$i=0;$errors=0;while($cycles===null||$i<$cycles){try{$this->tick();$errors=0;}catch(\Throwable $e){$errors++;if($cycles!==null&&$i+1>=$cycles)throw $e;} $i++;if($cycles===null||$i<$cycles){$delay=$this->interval*($errors?($this->backoff**min($errors,5)):1);if($this->jitter>0)$delay*=1+((random_int(-1000,1000)/1000)*$this->jitter);usleep((int)(max(1,$delay)*1_000_000));}}}
    private function save():void{if(!$this->stateFile||$this->last===null)return;$dir=dirname($this->stateFile);if(!is_dir($dir))@mkdir($dir,0775,true);@file_put_contents($this->stateFile,json_encode($this->last,JSON_PRETTY_PRINT|JSON_UNESCAPED_SLASHES),LOCK_EX);}
}
